url: ""
highlight: pygments
safe: false
permalink: pretty
paginate: 10
exclude:
    - fabfile.py
    - fabfile.pyc
    - README.md
    - etc
    - Gemfile
    - Gemfile.lock
gems:
    - jekyll-relative-links
    - jekyll-paginate
