baseURL: "/"
disablePathToLower: true
DefaultContentLanguage: "en"
languageCode: en-us
title: Thomas 'Toke' Kerpe
#theme: ""
contentdir: "content"
paginate: 5
relativeURLs: true
enableRobotsTXT: true
metaDataFormat: yaml
author: "Thomas Kerpe"
ignoreFiles:
  - ".gitkeep"
enableGitInfo: true

permalinks:
  post: /blog/:year/:month/:title/

params:
  author: "Thomas Kerpe"
  dateform: "2. Jan 2006"
  dateformfull: "Mon 2 Jan 2006 15:04:05 MST"
  description: "Toke's Blog"
  #copyright: "Copyleft by Thomas Kerpe"
  logo: "img/avatar.png"
  favicon: "assets/favicon.ico"
  highlightjs: false
  progressively: false
  latestpostcount: 5
  github: "toke"
  email: "toke@toke.de"
  twitter: "brxs"
  googlePlus: ThomasKerpe
  #social_banner: "img/banner.png"

menu:
  main:
    - name: "Blog"
      identifier: "blog"
      url: "/blog/"
      weight: 100
    - name: "Article"
      identifier: "article"
      url: "/article/"
      weight: 110
    - name: "Code"
      identifier: "code"
      url: "/code/"
      weight: 120
    - name: "Notes"
      identifier: "notes"
      url: "/note/"
      weight: 120
  footer:
    - name: "Impressum"
      identifier: "impress"
      url: "/impressum/"
      weight: 100
    - name: "Datenschutz"
      identifier: "privacy"
      url: "/datenschutz/"
      weight: 120
    - name: "Web"
      identifier: "web"
      url: "https://toke.de/"
      weight: 150
    - name: ".onion"
      identifier: "onion"
      url: "http://ptusz6326ongoogf.onion/"
      weight: 150
    - name: ".onion (v3)"
      identifier: "onion_v3"
      url: "http://tokedetqcrtejvmvhe3gwax44hwhfb6hmlrbkepkr423q5j6haom6zid.onion/"
      weight: 160
