---

baseURL: "/"
disablePathToLower: true
DefaultContentLanguage: "en"
languageCode: en-us
title: Thomas 'Toke' Kerpe
theme: "cocoa-eh"
contentdir: "content"
paginate: 5
relativeURLs: false
enableRobotsTXT: true
metaDataFormat: yaml
author: "Thomas Kerpe"
ignoreFiles:
  - ".gitkeep"
enableGitInfo: true

# Code pen
pygmentsUseClassic: false
pygmentsCodefences: true
pygmentsStyle: "pygments"


permalinks:
  post: /blog/:year/:month/:title/

params:
  author: "Thomas Kerpe"
  dateform: "2. Jan 2006"
  dateformfull: "Mon 2 Jan 2006 15:04:05 MST"
  description: "Toke's Blog"
  copyright: "The content of the site is released under CC BY-SA 4.0, unless stated otherwise."
  copyrightUrl: https://creativecommons.org/licenses/by-sa/4.0/
  logo: "img/avatar.png"
  logofile: "img/avatar.png"
  favicon: "assets/favicon.ico"
  extracssfiles:
    - css/toke.css
  highlightjs: false
  progressively: true
  noreadingtime: false
  blogs:
    - blog
    - code
    - note
    - article
  #large_banner_logo: true
  latestpostcount: 5
  github: "toke"
  email: "toke@toke.de"
  twitter: "brxs"
  keybase: "toke"
  # social_banner: "img/banner.png"
  issoHost: toke.de/isso/toke.de

menu:
  main:
    - name: "Blog"
      identifier: "blog"
      url: "/blog/"
      weight: 100
    - name: "Article"
      identifier: "article"
      url: "/article/"
      weight: 110
    - name: "Code"
      identifier: "code"
      url: "/code/"
      weight: 120
    - name: "Notes"
      identifier: "notes"
      url: "/note/"
      weight: 120
  footer:
    - name: "Impressum"
      identifier: "impress"
      url: "/impressum/"
      weight: 100
    - name: "Datenschutz"
      identifier: "privacy"
      url: "/datenschutz/"
      weight: 120
    - name: "Web"
      identifier: "web"
      url: "https://toke.de/"
      weight: 140
    - name: ".onion"
      identifier: "onion"
      url: "http://ptusz6326ongoogf.onion/"
      weight: 150
    - name: ".onion (v3)"
      identifier: "onion_v3"
      url: "http://tokedetqcrtejvmvhe3gwax44hwhfb6hmlrbkepkr423q5j6haom6zid.onion/"
      weight: 160
