baseURL: "/"
disablePathToLower: true
DefaultContentLanguage: "en"
languageCode: en-us
title: Thomas 'Toke' Kerpe
#theme: ""
contentdir: "content"
paginate: 5
relativeURLs: true
enableRobotsTXT: true
metaDataFormat: yaml
author: "Thomas Kerpe"
ignoreFiles:
  - ".gitkeep"

permalinks:
  post: /blog/:year/:month/:title/

params:
  dateform: "2. Jan 2006"
  dateformfull: "Mon 2 Jan 2006 15:04:05 MST"
  description: "Toke's Blog"
  #copyright: "Copyleft by Thomas Kerpe"
  logofile: "img/avatar.png"
  faviconfile: "assets/favicon.ico"
  highlightjs: true
  progressively: true
  latestpostcount: 3
  github: "toke"
  email: "toke@toke.de"
  twitter: "brxs"
  googlePlus: ThomasKerpe
  #social_banner: "img/banner.png"

menu:
  main:
    - name: "Blog"
      identifier: "blog"
      url: "/blog/"
      weight: 100
    - name: "Article"
      identifier: "article"
      url: "/article/"
      weight: 110
    - name: "Code"
      identifier: "code"
      url: "/code/"
      weight: 120
    - name: "Notes"
      identifier: "notes"
      url: "/note/"
      weight: 120
  footer:
    - name: "Impressum"
      identifier: "impress"
      url: "/impressum/"
